### PR TITLE
Switch HTML bundler to html-bundler-webpack-plugin

### PR DESCRIPTION
**Pull request by webdiscus**
Hello @bgausden,

This is the PR for the issue [Switch HTML bundler to html-bundler-webpack-plugin](https://github.com/bgausden/hsbc-web-app/issues/3).

I'm the author of the [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin) and I will help you to switch the HTML bundler.

You can start the development in the browser using the default command: `npm start`.

Using this plugin, HTML is an entry point and the source files of all assets can be specified directly in the HTML, similar to how it works in Vite or Parcel. The plugin replace the source files with their output filenames in the generated HTML.

Of cause you can import styles in JS, but it is the "bad practice".

The HTML bundler plugin replaces the functionality of the plugins and loaders:
- html-webpack-plugin
- mini-css-extract-plugin
- html-loader
- style-loader

### CODE REVIEW

**Comment by bgausden** [comment]
CSS is compiled and then loaded. It is not loaded from the bootstrap module.

**Comment by webdiscus** [comment]
> CSS is compiled and then loaded. It is not loaded from the bootstrap module.

 
Using the `bootstrap` module name in `href` is resolved the compiled CSS file defined in the `package.json` of the node module.
In `package.json` of `bootstrap` is defined the `bootstrap/dist/css/bootstrap.min.css` file.
Also using:
```html
<link href="bootstrap" rel="stylesheet" />
- OR -
<link href="bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
```

has  the same effect as you import it in JS:

```js
import 'bootstrap/dist/css/bootstrap.min.css'
```

In any case will be used Webpack loader rule defined in your config:
```js
             {
                    test: /\.(s?css)$/,
                    use: [{
                        loader: 'css-loader', // translates CSS into CommonJS modules
                    }, {
                        loader: 'postcss-loader', // Run post css actions
                        options: {
                            postcssOptions: {
                                plugins: function() { // post css plugins, can be exported to postcss.config.js
                                    return [
                                        require('precss'),
                                        require('autoprefixer')
                                    ];
                                }
                            }
                        }
                    }, {
                        loader: 'sass-loader' // compiles Sass to CSS
                    }]
                },
```

It's right.
What is wrong?

**Comment by webdiscus** [comment]
Of cause, you can add a separate rule for CSS only:
```js
{
  test: /\.(css)$/,
  loader: 'css-loader', 
}
```
Then loaded `bootstrap/dist/css/bootstrap.min.css` file will be processed only via `css-loader`.

**Comment by webdiscus** [comment]
I have added new rule to load compiled CSS from node_modules w/o compilation:
```js
              {
                    test: /\.css$/i,
                    include: /node_modules/,
                    loader: 'css-loader',
                },
```

Then the `bootstrap/dist/css/bootstrap.min.css` file will be loaded via `css-loader` only without compilation via `sas-loader`, `postcss-loader`.

**Comment by bgausden** [comment]
Sorry. Not clear. The project compiles src/index.scss and injects the resulting CSS into index.html. I can take a look at how this is accomplished in the next couple of days. Appreciate the PR - many thanks. /barryOn 29 Aug 2023, at 23:53, webdiscus ***@***.***> wrote:﻿
I have added new rule to load compiled CSS from node_modules w/o compilation:
              {
                    test: /\.css$/i,
                    include: /node_modules/,
                    loader: 'css-loader',
                },

**Comment by webdiscus** [comment]
@bgausden 

aha, ok. Good, then simple add the source SCSS file to HTML:
```html
<!-- load source style -->
<link href="./index.scss" rel="stylesheet" />
```

_./index.scss_

```scss
@import "custom";
// load source SCSS from bootstrap module
@import "bootstrap/scss/bootstrap.scss";
```

The source `index.scss` file will be automatically compiled and the extracted CSS can be inlined into HTML or saved into separate file to output directory. Currently, the extracted CSS is inlined into HTML.

I have updated the PR.

**Review by bgausden — APPROVED** [review]

**Pull request merged**
